version: '3'

services:
  postgres:
    container_name: postgres-csc2022
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - csc.env